name: app
type: "java:11"
disk: 1024
hooks:
    build: mvn clean package -DskipTest
relationships:
    database: "db:postgresql"
web:
    commands:
        start: java $JAVA_OPTS -jar target/micronaut-1.0-SNAPSHOT.jar