micronaut:
  application:
    name: jpa
datasources:
  default:
    url: ${JDBC-URL:`jdbc:postgresql://localhost:5432/micronaut`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC-USER:micronaut}
    password: ${JDBC-PASSWORD:micronaut}
jpa.default.properties.hibernate.hbm2ddl.auto: update
